name: Preview Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
  VITE_SUPABASE_KEY: ${{secrets.VITE_SUPABASE_KEY}}
  VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - run: npm ci
      - run: npm run test

  deploy-preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}

      - name: Build the project
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}

      - name: Deploy the project
        run: vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
